import 'package:flutter/material.dart'; import 'package:flutter_localizations/flutter_localizations.dart'; import 'package:flutter_riverpod/flutter_riverpod.dart'; import 'package:go_router/go_router.dart';
void main()=>runApp(const ProviderScope(child:SawnApp()));
class SawnApp extends ConsumerWidget{ const SawnApp({super.key}); @override Widget build(BuildContext context,WidgetRef ref)=>MaterialApp.router(debugShowCheckedModeBanner:false,title:'صَون',themeMode:ThemeMode.system,locale:const Locale('ar'),supportedLocales:const [Locale('ar'),Locale('en')],localizationsDelegates:GlobalMaterialLocalizations.delegates,theme:AppTheme.light,darkTheme:AppTheme.dark,routerConfig:router);}
final router=GoRouter(initialLocation:'/splash',routes:[GoRoute(path:'/splash',builder:(_,__)=>const SplashScreen()),...screens.map((s)=>GoRoute(path:s.path,builder:(_,__)=>FeatureScreen(spec:s)))]);
class ScreenSpec{final String path,title,subtitle; const ScreenSpec(this.path,this.title,this.subtitle);} 
const screens=[ScreenSpec('/onboarding','مرحباً بك في صَون','محفظة راتب ذكية لحياة مالية أهدأ'),ScreenSpec('/login','تسجيل الدخول','البريد، الجوال، Google، Apple'),ScreenSpec('/register','إنشاء حساب','ابدأ إدارة راتبك بأمان'),ScreenSpec('/otp','التحقق من الرمز','أدخل رمز التحقق لمرة واحدة'),ScreenSpec('/pin','إعداد الرقم السري','PIN مشفّر ومخزن بأمان'),ScreenSpec('/biometric','البصمة والوجه','دخول سريع وآمن'),ScreenSpec('/home','لوحة التحكم','الرصيد المتاح، المقفل، والتنبيهات'),ScreenSpec('/salary-setup','معالج إعداد الراتب','وزّع راتبك أسبوعياً أو حسب اختيارك'),ScreenSpec('/plans','خطط الراتب','إدارة الخطط والتدوير والفتح المبكر'),ScreenSpec('/plan-details','تفاصيل الخطة','المخصصات والقيود والرسوم'),ScreenSpec('/allocations','المخصصات','تحويل بين الفترات ومتابعة الفتح'),ScreenSpec('/wallet','المحفظة','الأرصدة، التحويلات، وسجل العمليات'),ScreenSpec('/transactions','العمليات','بحث وتصفية وتصدير'),ScreenSpec('/goals','أهداف الادخار','تقدم، ادخار تلقائي، ومكافآت'),ScreenSpec('/goal-details','تفاصيل الهدف','تحليلات وتوقعات الإنجاز'),ScreenSpec('/analytics','التحليلات','رسوم واتجاهات ورؤى ذكية'),ScreenSpec('/notifications','الإشعارات','تنبيهات فتح الرصيد والأسرة والأهداف'),ScreenSpec('/family','محفظة الأسرة','دعوات وصلاحيات وتحويلات'),ScreenSpec('/profile','الملف الشخصي','الهوية والتفضيلات'),ScreenSpec('/settings','الإعدادات','اللغة والأمان والإشعارات'),ScreenSpec('/language','اللغة','العربية والإنجليزية مع RTL كامل'),ScreenSpec('/security','الأمان','PIN، بصمة، جلسات، وسجل تدقيق'),ScreenSpec('/help','مركز المساعدة','أسئلة شائعة وتواصل'),ScreenSpec('/about','عن صَون','هوية سعودية عصرية للتقنية المالية')];
class AppTheme{static ThemeData get light=>ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff0f766e),brightness:Brightness.light),fontFamily:'Roboto'); static ThemeData get dark=>ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff2dd4bf),brightness:Brightness.dark));}
class SplashScreen extends StatelessWidget{const SplashScreen({super.key}); @override Widget build(BuildContext context)=>Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('صَون',style:TextStyle(fontSize:56,fontWeight:FontWeight.bold)),const Text('Smart Salary Wallet'),const SizedBox(height:24),FilledButton(onPressed:()=>context.go('/onboarding'),child:const Text('ابدأ'))])));}
class FeatureScreen extends StatelessWidget{final ScreenSpec spec; const FeatureScreen({super.key,required this.spec}); @override Widget build(BuildContext context)=>Directionality(textDirection:Directionality.of(context),child:Scaffold(appBar:AppBar(title:Text(spec.title)),body:ListView(padding:const EdgeInsets.all(20),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(spec.title,style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:8),Text(spec.subtitle),const SizedBox(height:20),const LinearProgressIndicator(value:.68),const SizedBox(height:20),Wrap(spacing:12,runSpacing:12,children:[FilledButton(onPressed:(){},child:const Text('حفظ')),OutlinedButton(onPressed:(){},child:const Text('تصدير PDF')),OutlinedButton(onPressed:()=>context.go('/home'),child:const Text('الرئيسية'))])]))),...List.generate(3,(i)=>ListTile(leading:const Icon(Icons.account_balance_wallet_outlined),title:Text('عنصر مالي ${i+1}'),subtitle:const Text('حالة فورية، دعم دون اتصال، وإمكانية مزامنة آمنة'),trailing:const Icon(Icons.chevron_right)))])));}
